# Generated by Django 2.2.5 on 2019-09-14 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='author',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='visibility',
        ),
    ]
