# Generated by Django 2.2.6 on 2019-11-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20191109_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='origin',
            field=models.ImageField(upload_to='photos/%y/%m/%d/', verbose_name='画像'),
        ),
    ]
