# Generated by Django 2.2.2 on 2019-06-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190613_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': '投稿'},
        ),
    ]
