# Generated by Django 2.2.6 on 2019-11-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.URLField(blank=True, verbose_name='参照URL'),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, verbose_name='参照URL'),
        ),
    ]
