# Generated by Django 2.2.6 on 2020-06-04 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191111_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image_origin',
            field=models.ImageField(blank=True, upload_to='featured_image/%y/%m/', verbose_name='メイン画像(option)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='url',
            field=models.URLField(blank=True, max_length=255, verbose_name='参照URL(option)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.Category', verbose_name='カテゴリー(option)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.Tag', verbose_name='タグ(option)'),
        ),
        migrations.AlterField(
            model_name='url',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='url',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='タイトル(option)'),
        ),
    ]
