# Generated by Django 2.2.6 on 2020-06-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200604_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='featured_image_origin',
            new_name='featured_image',
        ),
    ]
