# Generated by Django 2.2.3 on 2019-07-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190621_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
